//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBrouter_prj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelList
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public int Xval { get; set; }
        public int Yval { get; set; }
        public int PCBnum { get; set; }
        public int R_MotionShape_num { get; set; }
        public string R_MotionShape_distance_Y { get; set; }
        public string R_distance_X { get; set; }
        public string R_pos_Y { get; set; }
        public int C_MotionShape_num { get; set; }
        public string C_MotionShape_distance_X { get; set; }
        public string C_distance_Y { get; set; }
        public string C_pos_X { get; set; }
    }
}
