//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBrouter_prj.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCBrouterDBEntities : DbContext
    {
        public PCBrouterDBEntities()
            : base(@"metadata=res://*/Model.Model1.csdl|res://*/Model.Model1.ssdl|res://*/Model.Model1.msl;provider=System.Data.SqlClient;provider connection string=';data source=DESKTOP-QRDMR9C\SQLRAV;initial catalog=PCBrouterDB;user id=sa;password=13011408Bn;MultipleActiveResultSets=True';")
        {
            //@"metadata=res://*/Model.Model1.csdl|res://*/Model.Model1.ssdl|res://*/Model.Model1.msl;provider=System.Data.SqlClient;provider connection string=';data source=DESKTOP-FPLJSMH\KSTDATABASE;initial catalog=PCBrouterDB;user id=sa;password=13011408Bn;MultipleActiveResultSets=True';"
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ModelList> ModelLists { get; set; }
    }
}
